//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace semifinishAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class siixsem_models_t
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public siixsem_models_t()
        {
            this.siixsem_semi_fg_td = new HashSet<siixsem_semi_fg_td>();
            this.siixsem_semi_manu_td = new HashSet<siixsem_semi_manu_td>();
            this.siixsem_semi_smtt_td = new HashSet<siixsem_semi_smtt_td>();
            this.siixsem_semi_smtb_td = new HashSet<siixsem_semi_smtb_td>();
        }
    
        public int se_id { get; set; }
        public string se_description { get; set; }
        public string se_serial_pn_1 { get; set; }
        public string se_serial_pn_2 { get; set; }
        public string se_serial_pn_3 { get; set; }
        public string se_serial_pn_4 { get; set; }
        public string se_serial_pn_5 { get; set; }
        public System.DateTime se_created_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<siixsem_semi_fg_td> siixsem_semi_fg_td { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<siixsem_semi_manu_td> siixsem_semi_manu_td { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<siixsem_semi_smtt_td> siixsem_semi_smtt_td { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<siixsem_semi_smtb_td> siixsem_semi_smtb_td { get; set; }
    }
}
