//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace semifinishAdmin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class siixsem_wip_config_dbEntities : DbContext
    {
        public siixsem_wip_config_dbEntities()
            : base("name=siixsem_wip_config_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<siixsem_cgs_programs_t> siixsem_cgs_programs_t { get; set; }
        public virtual DbSet<siixsem_models_t> siixsem_models_t { get; set; }
        public virtual DbSet<siixsem_semi_fg_td> siixsem_semi_fg_td { get; set; }
        public virtual DbSet<siixsem_semi_manu_td> siixsem_semi_manu_td { get; set; }
        public virtual DbSet<siixsem_semi_smtb_td> siixsem_semi_smtb_td { get; set; }
        public virtual DbSet<siixsem_semi_smtt_td> siixsem_semi_smtt_td { get; set; }
        public virtual DbSet<siixsem_semifinish_t> siixsem_semifinish_t { get; set; }
    }
}
